name: Report Bug
description: Used to report bug
title: "[Bug]"
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Undecided
        - P1-Stopper
        - P2-High
        - P3-Medium
        - P4-Low
      default: 0
    validations:
      required: true

  - type: textarea
    id: Customer
    attributes:
      label: Customer info
      description: Customer name, business impact, potential deal (Chip Number, Money) and other.
      placeholder: Name, business impact, money.
    validations:
      required: true

  - type: dropdown
    id: customer-impact
    attributes:
      label: Customer impact level
      options:
        - Undecided
        - P1-Stopper
        - P2-High
        - P3-Medium
        - P4-Low
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: os
    attributes:
      label: OS type
      options:
        - label: Ubuntu
        - label: RedHat
        - label: SUSE
        - label: Windows
        - label: Mac
        - label: BSD
        - label: Other
    validations:
      required: true

  - type: checkboxes
    id: hardware
    attributes:
      label: Hardware type
      options:
        - label: Xeon-GNR
        - label: Xeon-EMR
        - label: Xeon-SPR
        - label: Xeon-ICX
        - label: Xeon-CLX
        - label: Xeon-other
        - label: Gaudi3
        - label: Gaudi2
        - label: Gaudi1
        - label: GPU-PVC
        - label: GPU-Flex
        - label: GPU-Arc
        - label: GPU-Arc-MTL
        - label: GPU-Nvidia
        - label: GPU-AMD
        - label: GPU-other
        - label: AI-PC (Please let us know in description)
        - label: CPU-other (Please let us know in description)
    validations:
      required: true

  - type: checkboxes
    id: install
    attributes:
      label: Installation method
      options:
        - label: Pull docker images from hub.docker.com
        - label: Build docker images from source
    validations:
      required: true

  - type: checkboxes
    id: deploy
    attributes:
      label: Deploy method
      options:
        - label: Docker compose
        - label: Docker
        - label: Kubernetes
        - label: Helm
    validations:
      required: true

  - type: dropdown
    id: node
    attributes:
      label: Running nodes
      options:
        - Single Node
        - Multiple Nodes
      default: 0
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: What's version?
      description: Docker ID in hub.docker.com or commit ID of Dockerfile.
      placeholder:
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description:
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Raw log
      description: Provide the log of RESTFul API or docker for micro-service by `docker logs CONTAINER`
      render: shell
    validations:
      required: false