name: Report Bug
description: Used to report bug
title: "Bug"
body:
  - type: checkboxes
    id: os
    attributes:
      label: OS type
      options:
        - Ubuntu
        - RedHat
        - SUSE
        - Windows
        - Mac
        - BSD
        - Other
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: hardware
    attributes:
      label: Hardware type
      options:
        - Xeon-GNR
        - Xeon-EMR
        - Xeon-SPR
        - Xeon-ICX
        - Xeon-CLX
        - Xeon-other
        - Gaudi3
        - Gaudi2
        - Gaudi1
        - GPU-PVC
        - GPU-Flex
        - GPU-Arc
        - GPU-Arc-MTL
        - GPU-Nvidia
        - GPU-AMD
        - GPU-other
        - AI-PC (Please let us know in description)
        - CPU-other (Please let us know in description)
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: install
    attributes:
      label: Installation method
      options:
        - Pull docker images from hub.docker.com
        - Build docker images from source
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: deploy
    attributes:
      label: Deploy method
      options:
        - Docker compose
        - Docker
        - Kubernetes
        - Helm
      default: 0
    validations:
      required: true

  - type: dropdown
    id: node
    attributes:
      label: Multiple nodes
      options:
        - Single Node
        - Multiple Nodes
      default: 0
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: What's version?
      description: Docker ID in hub.docker.com or commit ID of Dockerfile.
      placeholder:
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Undecided
        - P1-Stopper
        - P2-High
        - P3-Medium
        - P4-Low
      default: 0
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Description the problem
      description:
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Description the problem
      description: Provide the log of RESTFul API or docker for micro-service by `docker logs CONTAINER`
      render: shell
    validations:
      required: true
