name: Report Bug
description: Used to report bug
title: "Bug"
body:
  - type: checkboxes
    id: os
    attributes:
      label: OS type
      options:
        - Ubuntu
        - RedHat
        - SUSE
        - Windows
        - Mac
        - BSD
        - Other
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: hardware
    attributes:
      label: Hardware type
      options:
        - label: Xeon-GNR
        - label: Xeon-EMR
        - label: Xeon-SPR
        - label: Xeon-ICX
        - label: Xeon-CLX
        - label: Xeon-other
        - label: Gaudi3
        - label: Gaudi2
        - label: Gaudi1
        - label: GPU-PVC
        - label: GPU-Flex
        - label: GPU-Arc
        - label: GPU-Arc-MTL
        - label: GPU-Nvidia
        - label: GPU-AMD
        - label: GPU-other
        - label: AI-PC (Please let us know in description)
        - label: CPU-other (Please let us know in description)
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: install
    attributes:
      label: Installation method
      options:
        - label: Pull docker images from hub.docker.com
        - label: Build docker images from source
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: deploy
    attributes:
      label: Deploy method
      options:
        - label: Docker compose
        - label: Docker
        - label: Kubernetes
        - label: Helm
      default: 0
    validations:
      required: true

  - type: dropdown
    id: node
    attributes:
      label: Multiple nodes
      options:
        - label: Single Node
        - label: Multiple Nodes
      default: 0
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: What's version?
      description: Docker ID in hub.docker.com or commit ID of Dockerfile.
      placeholder:
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - label: Undecided
        - label: P1-Stopper
        - label: P2-High
        - label: P3-Medium
        - label: P4-Low
      default: 0
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Description the problem
      description:
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Description the problem
      description: Provide the log of RESTFul API or docker for micro-service by `docker logs CONTAINER`
      render: shell
    validations:
      required: true